### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AhrimanSefid** [vlnahp/Btcbf#12]
0%|                                                                                       | 17044/1e+16 [02:15<22138098990:39:34, 125.47it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "Btcbf.py", line 37, in check_list_online
    data = json.loads(url.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Btcbf.py", line 113, in <module>
    multiprocessing()
  File "Btcbf.py", line 110, in multiprocessing
    tuple(results)
  File "/usr/local/lib/python3.6/dist-packages/tqdm-4.62.3-py3.6.egg/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vlnahp** [comment]
It means: `the API limit reached`

**Comment by AhrimanSefid** [comment]
can add multi api?
or proxy add?

**Comment by vlnahp** [comment]
This is a free API. You can use a paid API account for more requests per day.

**Comment by AhrimanSefid** [comment]
ok, can help add api to scripts.

**Comment by vlnahp** [comment]
Do you know what an API is?

**Comment by mikejnpc** [comment]
really you asking someone do they know what a api is ? =/

**Comment by vlnahp** [comment]
> really you asking someone do they know what a api is ? =/ lol... well i wont post my error which inst api related :D

Based on his/her statements most probably he seems not to know what it is. I'm expecting your issue 😁
