### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by Ipertatos** [vlnahp/Btcbf#23]
`Starting ...
Running ...
multiprocessing.pool.RemoteTraceback:  elapsed time: 0.8minutes
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "Btcbf.py", line 48, in random_online_brute
    data = json.loads(url.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Btcbf.py", line 163, in <module>
    multiprocessing()
  File "Btcbf.py", line 159, in multiprocessing
    tuple(results)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

This happens at random times while running the script with option 4 and 1 selected

**Comment by vlnahp** [comment]
Already discussed [here](https://github.com/vlnahp/Btcbf/issues/12#issue-1083474826).
