### ISSUE TITLE
AttributeError: 'tqdm_tk' object has no attribute '_tk_window'

### ISSUE THREAD

**Issue by Prospero1** [vlnahp/Btcbf#3]
Seems to not work on raspberry (python 3) - also python doesn't want take bit

```
How many cores to be used? (leave empty to use all available cores): 4
Starting ...
Traceback (most recent call last):
  File "Btcbf.py", line 85, in <module>
    multiprocessing()
  File "Btcbf.py", line 80, in multiprocessing
    results = tqdm_tk(pool.imap_unordered(check_list, r), total=10e15)
  File "/usr/local/lib/python3.7/dist-packages/tqdm/tk.py", line 76, in __init__
    self._tk_window = tkinter.Tk()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
Exception ignored in: <function tqdm.__del__ at 0x75813858>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1152, in __del__
    self.close()
  File "/usr/local/lib/python3.7/dist-packages/tqdm/tk.py", line 123, in close
    self._tk_window.protocol("WM_DELETE_WINDOW", _close)
AttributeError: 'tqdm_tk' object has no attribute '_tk_window'

```

**Comment by vlnahp** [comment]
Removed tk. Clone again or update ``` Btcbf.py ``` contents to [the latest commit](https://github.com/vlnahp/Btcbf/blob/main/Btcbf.py)

Sorry, I can't understand the second part <**also python doesn't want take bit**>. Would please you explain more?
