### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Keeksy** [vlnahp/Btcbf#44]
After the recent update I did a test with a known address in sequential brute force mode and it doesn't seem to work. No results found. Looks like it doesn't read adress.txt

**Comment by Keeksy** [comment]
My bad, it works ok!

**Comment by Keeksy** [comment]
I never had the luck to actually bruteforce an address with balance 😅 I just did a test with a generated address from the sequence 1-100  it takes like 1 second for the program to find that key!

**Comment by Keeksy** [comment]
what error do you get?

**Comment by DasT1er** [comment]
Exception in thread Thread-1 (get_user_input):
Traceback (most recent call last):
  File "C:\Users\kopfn\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\kopfn\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Spiele\Neuer Ordner\Autohotkey\Neuer Ordner\Btcbf-main\Btcbf.py", line 151, in get_user_input
    print(f"resume range {r0[0]}-{r0[2]}")
IndexError: list index out of range

**Comment by vlnahp** [comment]
> Exception in thread Thread-1 (get_user_input): Traceback (most recent call last): File "C:\Users\kopfn\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner self.run() File "C:\Users\kopfn\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run self._target(*self._args, **self._kwargs) File "F:\Spiele\Neuer Ordner\Autohotkey\Neuer Ordner\Btcbf-main\Btcbf.py", line 151, in get_user_input print(f"resume range {r0[0]}-{r0[2]}") IndexError: list index out of range

Delete the `cache.txt` and run the program again.

**Comment by DasT1er** [comment]
thanks @vlnahp
