### ISSUE TITLE
brute2 don't work?

### ISSUE THREAD

**Issue by s6t6n66** [vlnahp/Btcbf#77]
use brute2
soft crash
brute1 working

**Comment by vlnahp** [comment]
Can you provide more information?

**Comment by mo1234-web** [comment]
For me too brute2 crash. I get this error: 
How many cores to be used? (leave empty to use all available cores):
Starting ...
  0%|                                                                                        | 0/1e+16 [00:00<?, ?it/s]Running ...
  0%|                                                                                        | 0/1e+16 [00:01<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "Btcbf.py", line 37, in check_list_online
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Btcbf.py", line 114, in <module>
  File "Btcbf.py", line 111, in multiprocessing
  File "tqdm\std.py", line 1178, in __iter__
  File "multiprocessing\pool.py", line 870, in next
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[11032] Failed to execute script Btcbf
